  final List<Map<String, dynamic>> profiles = [
    {
      'id': '1',
      'profile': 'paul.jpg',
      'nickname': 'pj',
      'fullname': 'Paul Julius Labrador',
      'blood type': 'B-',
      'donations': 5,
      'age': 29,
      'last donation': 'January 15, 2024',
      'address': '123 Elm Street, Springfield, IL',
      'phone': '+1 555-123-4567',
      'email': 'jakult69@email.com',
      'rank': 'ambassador',
    },
    {
      'id': '2',
      'profile': 'jibril.jpg',
      'nickname': 'Jiru',
      'fullname': 'Jibril Leandear Paul Rubi',
      'blood type': 'A-',
      'donations': 3,
      'age': 34,
      'last donation': 'December 5, 2023',
      'address': '456 Oak Avenue, Madison, WI',
      'phone': '+1 555-987-6543',
      'email': 'jlprui@email.com',
      'rank': 'regular',
    },
    {
      'id': '3',
      'profile': 'prof.jpg',
      'nickname': 'GarlicBread',
      'fullname': 'Daven Alajid',
      'blood type': 'O+',
      'donations': 1,
      'age': 22,
      'last donation': 'October 19, 2024',
      'address': '789 Pine Road, Chicago, IL',
      'phone': '+1 555-555-7890',
      'email': 'dabon@email.com',
      'rank': 'top',
    },
    {
      'id': '4',
      'profile': 'sayson.jpg',
      'nickname': 'cutiepie',
      'fullname': 'Davin Klein Sayson',
      'blood type': 'AB-',
      'donations': 2,
      'age': 28,
      'last donation': 'November 18, 2023',
      'address': '321 Maple Drive, Peoria, IL',
      'phone': '+1 555-321-4321',
      'email': 'princess0_0@email.com',
      'rank': 'occasional',
    },
    {
      'id': '5',
      'profile': 'zeldrex.jpg',
      'nickname': 'Splakoy',
      'fullname': 'Zeldrex June Inso',
      'blood type': 'O-',
      'donations': 6,
      'age': 39,
      'last donation': 'January 22, 2024',
      'address': '654 Birch Boulevard, Rockford, IL',
      'phone': '+1 555-222-3456',
      'email': 'TotalShell@email.com',
      'rank': 'leader',
    }
  ];
